### ISSUE TITLE
404 (instead of redirect) on deposit pages

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#111] opened 2020-07-22 17:30 UTC
As per discussion with @ajsutton in https://github.com/ethereum/eth2.0-deposit-cli/issues/53, reloading a page in the flow results in a 404.

The idea is that it is not possible to skip ahead in the process. It is intentional user friction to ensure that everyone goes through the steps. That said, it is not supposed to 404, it should just redirect you to the home page.

IIRC, it used to redirect back to the beginning.

**Comment by Battenfield** [comment] 2020-07-23 05:31
@ajsutton @CarlBeek Is this showing a netlify "not found" error or a launchpad rainbow background 404 error? I think this may have to do with our Netlify deployment as I only see this in that environment? Possibly caused by the password protection we have.

**Comment by Battenfield** [comment] 2020-07-27 15:36
Fixed in #127 and shipped in #128. This was a Netlify environment issue where we had to set up a redirect to the app so it will use react-router

**Closed by Battenfield** 2020-07-27 15:36 UTC
Labels: bug, help wanted
